### ISSUE TITLE
Allow inital selected image to be specified

### ISSUE THREAD

**Issue by shimwell** [jrieke/streamlit-image-select#2]
Thanks for making this super useful component.

I was wondering if it might be possible to specify the image that is selected when the app first loads. Perhaps this could default to None.

The regular streamlit select box makes use of a argument called index to perform this

**Comment by jrieke** [comment]
Thanks! :heart: I added an `index` parameter with 0.4.0. Wanted to do this in the beginning already and even had a TODO in my code. Not sure how I missed that.

**Comment by shimwell** [comment]
Amazing thanks so much.
