### ISSUE TITLE
Correct code for streamlit 1.19.0

### ISSUE THREAD

**Issue by DimIsaev** [jrieke/streamlit-image-select#8]
```st.experimental_memo is deprecated. Please use the new command st.cache_data instead, which has the same behavior. More information [in our docs](https://docs.streamlit.io/library/advanced-features/caching).```

please correct code for streamlit 1.19.0
Thanks

**Comment by mohamedserag1975** [comment]
when should we expect this to be corrected?

**Comment by jrieke** [comment]
Fixed in 0.6.0. Let me know if there are still problems!

**Comment by mohamedserag1975** [comment]
Thank you Jrieke, found out the streamlit-extras chart container still using experimental memo. hope [arnaudmiribel](https://github.com/arnaudmiribel) gets my message and fixes it in the repo where people download it.. I fixed mine on the local machine for now
